calculate note score(2)
Certune/Certune_Android pull request #15
Opened 2022-02-10 07:55 UTC by nitronium102

[음정 점수 산출]
1. songDB에서 소절별로 note 정보를 가져옵니다.
2. userDB에서 소절별로 note 정보를 가져온 후, songDB에서 가져온 기준 note와 비교하여 점수를 산출합니다.
3. 계산이 완료된 arrayList를 hashmap으로 만들어서 db에 업로드합니다.

[에러 해결]
**1. 동시간대에 addDataToFireStore, getUserMusicInfo, calcScore가 실행되는 오류**
-> 각각의 함수를 따로 호출하는 것이 아니라 첫 번째 함수가 성공하면 그 안에서 다른 함수를 호출하는 방법으로 해결했습니다.(addDataToFireStore이 성공하면 getUserMusicInfo를, getUserMusicInfo가 성공하면 calcScore가 실행되는 식)
**2. score이 100 이상 나오는 오류**
-> songDB와 userDB에 사용되는 변수를 섞어쓰고 있어서 발생했습니다. 변수를 분리하여 해결했습니다.
**3. getUserMusicInfo에서 NullPointerException이 나는 오류**
-> 현재 ProcessPitchRange에 모든 값이 들어가 있지 않아 발생하는 오류입니다. 일단 임시적으로 else 문에 ArrayList를 넣어 리턴하도록 하였습니다.

2022-02-10 07:56 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/ProcessNoteRange.java
> +            }
3번 에러 때문에 임시값을 넣어놓았습니다. 나중에 변경이 필요합니다.

2022-02-10 07:57 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +                        for (int i = 0; i < Objects.requireNonNull(list).size(); i++) {
NullPointerException을 방지하기 위해 넣었는데...@choala 가 제안한 것처럼 아예 try-catch문을 사용하고 NullPointerException이 나오면 뷰에서 알람을 띄우는 방식도 괜찮을 것 같습니다.

2022-02-10 07:58 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +                            Log.v("ERROR", "not enough records for calculating");
@choala 가 제시했던 try-catch문 안에 넣는 방법입니다.

2022-02-10 07:59 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +            sentenceTimeList.add(sentenceTime);
songDB에서 먼저 모든 값을 받아와 ArrayList에 넣고 이후에 userDB 관련 로직을 실행합니다.

2022-02-10 08:01 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
>                  }
flag = 범위에서 벗어난 note가 있을 경우 true로 설정합니다.
만약 flag가 true라면 userSentenceTime에서 (현재 note의 시작 시간 - 잘못된 note의 시작 시간)를 빼줍니다.

2022-02-10 08:04 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
>                  }
1) 소절 범위 내에 있고
2) user note의 시작 시간이 기준 note의 시간에 포함되어 있으면 
3) user note의 음정이 기준 note의 음정 범위 내인지 확인합니다.

2022-02-10 08:11 UTC, choala requested changes
Objects.requireNonNull()을 사용하면 null 값일시 NullPointerException이 발생하므로 이를 처리하기위해서 try-catch 문을 사용 해야할 것 같습니다.

2022-02-10 08:17 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +                            Log.v("NULL POINT ERROR", "not enough records for calculating");
📒Object.requireNotNull()은 시스템 상에서 not null을 보장한다는 의미가 아니라 개발자에게 이 값이 not null이어야 한다고 명시하는 용도로 쓰인다. 
-> requireNotNull() : 매개변수의 값이 null이 아니면 value를 반환, null이면 throw IllegalArgumentException(적절하지 않은 인자를 전달했을 때 발생시키는 Exception)

2022-02-10 08:18 UTC, nitronium102 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +                        } catch (Exception e) {
null이면 IllegalArgumentException을 던진다고 해서 NullPointerException 대신 일반적인 Exception을 받도록 했습니다!

2022-02-10 08:20 UTC, choala approved these changes
LGTM🙂

2022-02-10 08:22 UTC, emili5 approved these changes
Great!

2022-02-10 08:22 UTC, merged

2022-02-14 14:16 UTC, emili5 commented on app/src/main/java/com/techtown/tarsosdsp_pitchdetect/MainActivity.java
> +                        for (int i = 0; i < Objects.requireNonNull(list).size(); i++) {
좋아요~